apiVersion: v1
kind: Service
metadata:
  namespace: test
  labels:
    app: kubesphere-test-svc
  name: kubesphere-test-svc
spec:
  sessionAffinity: None
  selector:
    app: kubesphere-test
  ports:
    - name: http-80
      protocol: TCP
      targetPort: 8080
      port: 8080
